# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'swift_two' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift_two

  target 'swift_twoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift_twoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'AFNetworking'
  
  pod 'SVProgressHUD'
  
  pod 'MJExtension'

end
